# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ant_simulation/simsnapshot.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'ant_simulation/simsnapshot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ant_simulation/simsnapshot.proto\x12\x0e\x61nt_simulation\"\x92\x01\n\x0bSimSnapshot\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x61nt_ids\x18\x02 \x03(\x0c\x12&\n\x04\x61nts\x18\x03 \x03(\x0b\x32\x18.ant_simulation.AntState\x12*\n\x06\x63rumbs\x18\x04 \x03(\x0b\x32\x1a.ant_simulation.CrumbState\x12\x12\n\ncreated_at\x18\x05 \x01(\x03\"\x9a\x01\n\x08\x41ntState\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\x10\n\x08rotation\x18\x03 \x01(\x01\x12\x1d\n\x15pheremone_sensitivity\x18\x04 \x01(\x01\x12\x1a\n\x12pheremone_strength\x18\x05 \x01(\x01\x12\r\n\x05speed\x18\x06 \x01(\x01\x12\x1c\n\x14seconds_of_life_left\x18\x07 \x01(\x01\"0\n\nCrumbState\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\x0c\n\x04size\x18\x03 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ant_simulation.simsnapshot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIMSNAPSHOT']._serialized_start=53
  _globals['_SIMSNAPSHOT']._serialized_end=199
  _globals['_ANTSTATE']._serialized_start=202
  _globals['_ANTSTATE']._serialized_end=356
  _globals['_CRUMBSTATE']._serialized_start=358
  _globals['_CRUMBSTATE']._serialized_end=406
# @@protoc_insertion_point(module_scope)
