services:
  auth-service:
    build:
      context: .
      dockerfile: ./services/auth/Dockerfile
    command: uv run fastapi dev main.py --host 0.0.0.0 --port 8000 --root-path /auth
    env_file:
      - ./services/auth/.docker.env
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./services/auth/app:/services/app/app:ro
      - ./services/auth/main.py:/services/app/main.py:ro
      - ./shared:/shared:ro

  simulator-service:
    build:
      context: .
      dockerfile: ./services/simulator/Dockerfile
    command: uv run main.py
    env_file:
      - ./services/simulator/.docker.env
    expose:
      - "8000"
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ./services/simulator/app:/services/app/app:ro
      - ./services/simulator/main.py:/services/app/main.py:ro
      - ./shared:/shared:ro

  stream-service:
    build:
      context: .
      dockerfile: ./services/stream/Dockerfile
    command: uv run fastapi dev main.py --host 0.0.0.0 --port 8000 --root-path /stream
    env_file:
      - ./services/stream/.docker.env
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ./services/stream/app:/services/app/app:ro
      - ./services/stream/main.py:/services/app/main.py:ro
      - ./shared:/shared:ro

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./utilities/nginx/docker.nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    expose:
      - "80"
    environment:
      - NGINX_HOST=0.0.0.0
      - NGINX_PORT=80
    restart: unless-stopped
    depends_on:
      - auth-service

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: antsworld
      POSTGRES_USER: antsworld
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U antsworld -d antsworld"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data # Persist data with a volume

  redis:
    image: redis:7-alpine
    expose:
      - "6379"
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data

  pgadmin:
    build: ./utilities/pgadmin
    attach: false
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@ants.world
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5050:80"
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  db_migrator:
    build:
      context: .
      dockerfile: ./utilities/migrator/Dockerfile
    environment:
      - DATABASE_URL=postgresql://antsworld:password@db:5432/antsworld
    command: ["uv", "run", "alembic", "upgrade", "head"]
    restart: no
    depends_on:
      - db

volumes:
  db_data:
  pgadmin_data:
  redis_data:
